### ISSUE TITLE
How to access streamed data

### ISSUE THREAD

**Issue by stephaaaaan** [multichannelsystems/McsUsbNet_Examples#10]
Hello,

maybe a bit of a newbie question, but I do not really find the given explanations helpful so far. I was able to run `Recording.py` and it returned a few lines ".NET ....". 
How do I access this datastream, are there any more explanations apart from the example scripts and the 860-page "documentation" in McsUsbNet to get started with the basics?

**Comment by JensMCS** [comment]
Could you be a little bit more specific where you need help?
As you see in the code of the printout .NET ....": np_data contains the data from the device.
Regards the examples as important part of the documentation. The 860-pages are more a reference manual as an introduction

**Comment by stephaaaaan** [comment]
Thank you for the reply @JensMCS.

> The 860-pages are more a reference manual as an introduction
But in your README you write that this is the documentation. I think overall a lot of people would benefit from improved documentation for these two repositories (`McsUsbNet` and `McsUsbNet_Examples`). 
For the examples, it would be nice if you could indicate how one can really access the data that is streamed from the setup to my PC. As I understand it, these .NET files are unique to windows. I personally never work with windows and have no idea how to work with these files. 

I think my main questions would be:
- How do i connect the output of `recording.py` with `asNumpyArray()` while recording? 
- Where is this data stored? Is it lingering around in the RAM? What happens when the allocated space is full?

For the `McsUsbNet` I'd recommend extensive documentation that is understandable for people new to your library (e.g. on https://readthedocs.org/). In the current reference, the input parameters are listed but not explained. Also, the function description often does not explain what the function does in the end. Examples would be very helpful in this context.


Can you give some additional information of
