### ISSUE TITLE
C# MEA demo app throws 'Operation not supported' on StartDacq.

### ISSUE THREAD

**Issue by HaraldBarzan** [multichannelsystems/McsUsbNet_Examples#2]
Hello,

We have been using a USB-ME64 device in our lab for years and have been generally very pleased with it. Recently we started a new project for which we need to do closed loop experiments in which we vary the parameters of a stimulus according to some features in the recorded data in real time.  Our goal is then to write a C#/.NET app to implement this.

I'm having issues running the C# demo on my machine - it recognizes the MEA-USB64 device with no issues, but when I click 'Start' and the handler calls StartDacq(), the device throws an 'Operation not supported' exception (Status: 3760128005). I tried running the MC_Rack software (which, I suspect, also uses McsUsbNet) on this same machine and it works with no issues. Here I would add that our MC_Rack setup is configured for 32 analog channels, while the demo seems to use all 64. I've tried passing '32' to device.SetNumberOfChannels instead of 64, but it doesn't solve the issue.

Is there something I'm missing/doing wrong?

**Comment by JensMCS** [comment]
You most probably need a newer version of our USB driver. Best you install Multi Channel Experimeter from our web site [https://www.multichannelsystems.com/software/multi-channel-experimenter]. It includes the latest driver. Our latest official MC_Rack version was already released some time ago and the driver is missing a feature required by our latest McsUsbNet.dll.

**Comment by HaraldBarzan** [comment]
Thank you. This solved my problem.
