### ISSUE TITLE
Possible Expansion of STG channels?

### ISSUE THREAD

**Issue by satabios** [multichannelsystems/McsUsbNet_Examples#3]
I'm using a MEA1200 which has 3 independent stimulus generators (Stg1, Stg2, Stg3) to configure the patterns for each of them. 
As in the stimulus generators can be extended ( say can we add a new Stg4 or more )?

I'm using python and the latest McsUsbNet-5.1.6.DLL to run my script. Thanks in advance.

**Comment by armwal** [comment]
Hi, unfortunately not, because this is determined by the number of stimulation channels built into the MEA2100 headstage.. and there are just 3 of them. Nothing that can be changed by software, this is a hardware limitation...
