### ISSUE TITLE
device.StartDacq() Operation not supported in Matlab

### ISSUE THREAD

**Issue by gchassink** [multichannelsystems/McsUsbNet_Examples#6]
In McsUsbNet_3.2.45 device.StartDacq() worked, in McsUsbNet-5.1.24.0 it no longer works: matlab error "Operation not supported"
device MCS-IFB_Lite MEA2100

**Comment by armwal** [comment]
One possibility for the "Operation not supported" error might be that the installed driver for MCS devices is too old. Could you please download and install the current version of the Multi Channel Experimenter (https://www.multichannelsystems.com/software/multi-channel-experimenter)? This will also install the most recent driver and ensure that McsUsbNet.dll V 5.1.24 is compatible with it.

Armin

**Comment by gchassink** [comment]
Hi Armin,

Indeed downloading the latest version solved that problem. I’m getting more errors, further down the road. But up till now they have to do with formatting changes of the input arguments and output arguments and are solvable.

Thanks for now,

Gerco

**Comment by armwal** [comment]
Hi Gerco,

ok, thanks for the update! I'll close this issue now, feel free to open a new one in case you need help with one of the other errors.

Armin

**Comment by gchassink** [comment]
Solved by updating to the latest driver for the MCS device

**Comment by gchassink** [comment]
Hi Armin,
Thanks for the very quick response.
I am not a professional programmer, so please be patient with me.
In the attached script I copied the parts of my application that involve the communication with the MEA device.

If you need more, I can send you the complete folder as well, just let me know.

It is based on examples MCS has provided in the past.

Gerco
